### PR TITLE
Upgrade webpack to official 3.x version.

### LINKED ISSUE #30: Switch to official webpack
The official webpack 2.x has released for a long time. Even the webpack 3.x has been released last week. It should switch to the official release.

### PR DESCRIPTION
**Pull request by lijunle**
Resolve #30

### CODE REVIEW

**Comment by lijunle** [comment]
Hi, @christopheranderson Do you have any update about this?

**Comment by lijunle** [comment]
Thank you @christopheranderson for merging this PR! When can I see the changes on production?

**Comment by christopheranderson** [comment]
I'll do some e2e testing plus a few bug fixes, then release by Friday afternoon, PDT. Maybe earlier if I find some extra time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lijunle** [comment]
Thank you! It is awesome!

2017年8月29日 15:36，"Christopher Anderson" <notifications@github.com>写道：

**Comment by lijunle** [comment]
Hi, @christopheranderson 

Funcpack has already in v0.3.x, but Kudu is still using v0.2.2. Is there any way to use the newer version in Kudu?

**Comment by christopheranderson** [comment]
Whoops, sorry the delay. I've created a tracking item for this and I'll get it done this sprint. https://github.com/Azure/azure-functions-pack/issues/64

**Comment by lijunle** [comment]
Awesome! Thank you very much!

**Pull request merged**
