### PR TITLE
Updating repository in package.json

### PR DESCRIPTION
**Pull request by nelak**

### CODE REVIEW

**Comment by christopheranderson** [comment]
Good catch! Would you please open this against the `dev` branch, not `master`?

**Comment by nelak** [comment]
@christopheranderson It's opened against dev already.
Also I don't know if this is required but you may want to change the author to Microsoft Corporation and the contributors tag.

**Comment by christopheranderson** [comment]
Ah, whoops. Caught a mistake of mine. I'll clean up the package.json.

**Comment by christopheranderson** [comment]
This is now on latest

**Pull request merged**
